### ISSUE TITLE
using the GPU does not improve the calculation speed

### ISSUE THREAD

**Issue by YimingZhang0708** [rcdaudt/fully_convolutional_change_detection#5]
Hi Rodrigo,
Your work is so awesome and I am trying to learn everything. But I am new. When I run the code in GPU, the cost time is similar to the time in CPU, both almost 7 hours. And when I tried to adjust the batch_size from 32 to 128, it was even slower. I am not sure why the results shows like that, could you give some advice?
Thank you so much and best,
Yiming

**Comment by pvmilk** [comment]
I am checking the code and apparently, the issue is during validation.
Batch calculation is not used. One image is calculated at the time, which probably result in long calculation time.
